#!/usr/bin/env python3
"""
Run GNN inference on new δ-T features generated by `prepare_inference_data.py`.

The script keeps graph/connectivity identical to training artefacts stored in
`data/gnn_ready/` (or a custom directory). It performs the minimal steps:

1. Load artefacts from training (edge_index.pt, station_mapping.json,
   train_feature_names.json).
2. Load the CSV generated by `prepare_inference_data.py`.
3. Filter unknown stations, map `station_id` → `node_idx`.
4. Arrange feature matrix in the exact order used during training.
5. Build a `torch_geometric.data.Data` object and run the trained model.
6. Save predictions alongside the original rows.

Usage example
-------------
python scripts/run_gnn_inference.py \
  --features_csv data/inference/inference_features.csv \
  --gnn_dir data/gnn_ready \
  --model_path experiments/gnn/best_model.pt \
  --output_csv data/inference/inference_predictions.csv
"""

import argparse
import json
from pathlib import Path

import numpy as np
import polars as pl
import torch
from torch_geometric.data import Data

# project imports
import sys
project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(project_root))

from src.models.gnn_models import create_gnn_model  # factory

# ---------------------------------------------------------------------------
# util helpers (lightweight reuse of logic from deprecated/test_model.py)
# ---------------------------------------------------------------------------

def load_graph_artifacts(gnn_dir: Path):
    """Load edge_index, mapping and feature ordering from training directory."""
    edge_index = torch.load(gnn_dir / "edge_index.pt", weights_only=False)

    with open(gnn_dir / "station_mapping.json", "r") as f:
        mapping = {int(k): v for k, v in json.load(f).items()}

    with open(gnn_dir / "train_feature_names.json", "r") as f:
        feat_names = json.load(f)["features"]

    return edge_index, mapping, feat_names


def load_trained_model(model_path: Path, num_features: int, num_targets: int):
    """Load model checkpoint stored by train_gnn.py and map class names to factory types."""
    ckpt = torch.load(model_path, map_location="cpu", weights_only=False)

    raw_type = ckpt.get("model_type") or ckpt.get("model_class")
    if raw_type is None:
        raise ValueError("Could not infer model type from checkpoint.")

    # map possible class names to the factory keywords expected by `create_gnn_model`
    mapping = {
        'temporalgcn': 'gcn',
        'spatialgat': 'gat',
        'graphsage': 'sage',
        'graphtransformer': 'transformer',
        'hybridspatiotemporalgnn': 'hybrid',
    }
    model_type = mapping.get(str(raw_type).lower(), str(raw_type).lower())

    # configuration stored in checkpoint (optional)
    if "model_init_params" in ckpt:
        config = ckpt["model_init_params"]
    elif "config" in ckpt and isinstance(ckpt["config"], dict):
        config = ckpt["config"].get("model_params", {})

    # ensure we only keep args that the factory will accept
    allowed_keys = {"hidden_dim", "num_layers", "num_heads", "dropout", "use_batch_norm", "activation", "attention_dropout", "aggregation", "use_temporal", "temporal_dim"}
    config = {k: v for k, v in config.items() if k in allowed_keys}

    model = create_gnn_model(model_type=model_type, num_features=num_features,
                             num_targets=num_targets, **config)

    state_dict = ckpt.get("state_dict") or ckpt.get("model_state_dict")

    # adapt state dict keys if necessary (DataParallel or BatchNorm API changes)
    adapted_state_dict = {}
    for k, v in state_dict.items():
        new_k = k
        # remove leading 'module.' from DataParallel
        if new_k.startswith('module.'):
            new_k = new_k[len('module.'):]  # strip root prefix
        # if checkpoint saved BatchNorm via `BatchNorm` wrapper (.module), drop that token
        if '.module.' in new_k:
            new_k = new_k.replace('.module.', '.')
        adapted_state_dict[new_k] = v

    # load with strict=False to ignore any unmatched buffers (e.g., num_batches_tracked)
    missing, unexpected = model.load_state_dict(adapted_state_dict, strict=False)
    if missing:
        print(f"Warning: {len(missing)} missing keys while loading checkpoint (ignored). Example: {missing[:5]}")
    if unexpected:
        print(f"Warning: {len(unexpected)} unexpected keys in checkpoint (ignored). Example: {unexpected[:5]}")

    model.eval()
    return model


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Run inference with a trained GNN model")
    parser.add_argument("--features_csv", required=True, help="CSV generated by prepare_inference_data.py")
    parser.add_argument("--gnn_dir", default="data/gnn_ready", help="Directory with training graph artefacts")
    parser.add_argument("--model_path", required=True, help="Path to trained model checkpoint (.pt)")
    parser.add_argument("--output_csv", required=True, help="Where to save predictions w/ original data")
    parser.add_argument("--device", default="cpu", help="Inference device (cpu / cuda)")
    args = parser.parse_args()

    gnn_dir = Path(args.gnn_dir)
    edge_index, station_map, feat_names = load_graph_artifacts(gnn_dir)
    print(f"Loaded graph artefacts from {gnn_dir}: {edge_index.shape[1]} edges, {len(station_map)} stations")

    # Load inference features CSV
    df = pl.read_csv(args.features_csv, try_parse_dates=True)
    original_len = len(df)
 
    # --- efficient mapping via join ---------------------------------------
    mapping_df = pl.DataFrame({
        "station_id": list(station_map.keys()),
        "node_idx": list(station_map.values())
    }).with_columns(pl.col("station_id").cast(pl.Int64), pl.col("node_idx").cast(pl.Int64))

    # ensure type alignment before join
    df = df.with_columns(pl.col("station_id").cast(pl.Int64))

    df_before = len(df)
    df = df.join(mapping_df, on="station_id", how="inner")
    dropped = df_before - len(df)
    if dropped > 0:
        print(f"Warning: {dropped} rows dropped due to unseen station_id")

    df = df.sort(["node_idx", "datetime"])

    # Arrange features
    X = df.select(feat_names).to_numpy(writable=False)
    X = np.nan_to_num(X)
    x = torch.tensor(X, dtype=torch.float32)

    data_inf = Data(x=x, edge_index=edge_index, num_nodes=len(station_map))

    # Load model
    with open(Path(args.gnn_dir) / "train_feature_names.json", "r") as f:
        meta = json.load(f)
    num_targets = meta["n_targets"]

    model = load_trained_model(Path(args.model_path), num_features=len(feat_names), num_targets=num_targets)
    model = model.to(args.device)

    print("Running inference…")
    with torch.no_grad():
        preds = model(data_inf.to(args.device))
    preds_np = preds.cpu().numpy()

    # Save predictions alongside original rows
    out_df = df.with_columns(pl.Series("prediction", preds_np.flatten()))
    Path(args.output_csv).parent.mkdir(parents=True, exist_ok=True)
    out_df.write_csv(args.output_csv)
    print(f"✓ Predictions saved to {args.output_csv} ({len(out_df)} rows)")


if __name__ == "__main__":
    main() 